//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v3

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CDNMetrics) DeepCopyInto(out *CDNMetrics) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CDNMetrics.
func (in *CDNMetrics) DeepCopy() *CDNMetrics {
	if in == nil {
		return nil
	}
	out := new(CDNMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheRule) DeepCopyInto(out *CacheRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheRule.
func (in *CacheRule) DeepCopy() *CacheRule {
	if in == nil {
		return nil
	}
	out := new(CacheRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContentDeliveryNetwork) DeepCopyInto(out *ContentDeliveryNetwork) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContentDeliveryNetwork.
func (in *ContentDeliveryNetwork) DeepCopy() *ContentDeliveryNetwork {
	if in == nil {
		return nil
	}
	out := new(ContentDeliveryNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContentDeliveryNetwork) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContentDeliveryNetworkList) DeepCopyInto(out *ContentDeliveryNetworkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ContentDeliveryNetwork, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContentDeliveryNetworkList.
func (in *ContentDeliveryNetworkList) DeepCopy() *ContentDeliveryNetworkList {
	if in == nil {
		return nil
	}
	out := new(ContentDeliveryNetworkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContentDeliveryNetworkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContentDeliveryNetworkNode) DeepCopyInto(out *ContentDeliveryNetworkNode) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContentDeliveryNetworkNode.
func (in *ContentDeliveryNetworkNode) DeepCopy() *ContentDeliveryNetworkNode {
	if in == nil {
		return nil
	}
	out := new(ContentDeliveryNetworkNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContentDeliveryNetworkNode) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContentDeliveryNetworkNodeList) DeepCopyInto(out *ContentDeliveryNetworkNodeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ContentDeliveryNetworkNode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContentDeliveryNetworkNodeList.
func (in *ContentDeliveryNetworkNodeList) DeepCopy() *ContentDeliveryNetworkNodeList {
	if in == nil {
		return nil
	}
	out := new(ContentDeliveryNetworkNodeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ContentDeliveryNetworkNodeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContentDeliveryNetworkNodeSpec) DeepCopyInto(out *ContentDeliveryNetworkNodeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContentDeliveryNetworkNodeSpec.
func (in *ContentDeliveryNetworkNodeSpec) DeepCopy() *ContentDeliveryNetworkNodeSpec {
	if in == nil {
		return nil
	}
	out := new(ContentDeliveryNetworkNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContentDeliveryNetworkNodeStatus) DeepCopyInto(out *ContentDeliveryNetworkNodeStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContentDeliveryNetworkNodeStatus.
func (in *ContentDeliveryNetworkNodeStatus) DeepCopy() *ContentDeliveryNetworkNodeStatus {
	if in == nil {
		return nil
	}
	out := new(ContentDeliveryNetworkNodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContentDeliveryNetworkSpec) DeepCopyInto(out *ContentDeliveryNetworkSpec) {
	*out = *in
	in.DNS.DeepCopyInto(&out.DNS)
	if in.CDNNodes != nil {
		in, out := &in.CDNNodes, &out.CDNNodes
		*out = make([]ContentDeliveryNetworkNode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CacheRules != nil {
		in, out := &in.CacheRules, &out.CacheRules
		*out = make([]CacheRule, len(*in))
		copy(*out, *in)
	}
	if in.SSLConfig != nil {
		in, out := &in.SSLConfig, &out.SSLConfig
		*out = new(SSLConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContentDeliveryNetworkSpec.
func (in *ContentDeliveryNetworkSpec) DeepCopy() *ContentDeliveryNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(ContentDeliveryNetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContentDeliveryNetworkStatus) DeepCopyInto(out *ContentDeliveryNetworkStatus) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
	out.Metrics = in.Metrics
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContentDeliveryNetworkStatus.
func (in *ContentDeliveryNetworkStatus) DeepCopy() *ContentDeliveryNetworkStatus {
	if in == nil {
		return nil
	}
	out := new(ContentDeliveryNetworkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainNameSystem) DeepCopyInto(out *DomainNameSystem) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainNameSystem.
func (in *DomainNameSystem) DeepCopy() *DomainNameSystem {
	if in == nil {
		return nil
	}
	out := new(DomainNameSystem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DomainNameSystem) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainNameSystemList) DeepCopyInto(out *DomainNameSystemList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DomainNameSystem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainNameSystemList.
func (in *DomainNameSystemList) DeepCopy() *DomainNameSystemList {
	if in == nil {
		return nil
	}
	out := new(DomainNameSystemList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DomainNameSystemList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainNameSystemSpec) DeepCopyInto(out *DomainNameSystemSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainNameSystemSpec.
func (in *DomainNameSystemSpec) DeepCopy() *DomainNameSystemSpec {
	if in == nil {
		return nil
	}
	out := new(DomainNameSystemSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainNameSystemStatus) DeepCopyInto(out *DomainNameSystemStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainNameSystemStatus.
func (in *DomainNameSystemStatus) DeepCopy() *DomainNameSystemStatus {
	if in == nil {
		return nil
	}
	out := new(DomainNameSystemStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSLConfig) DeepCopyInto(out *SSLConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSLConfig.
func (in *SSLConfig) DeepCopy() *SSLConfig {
	if in == nil {
		return nil
	}
	out := new(SSLConfig)
	in.DeepCopyInto(out)
	return out
}
